"""New exact scope guard; the lower-bound source is the original first-event exit subsource.
Analytical w/G_c bounds are proved in the companion markdown, not generated by this code.
This does not test a weak endpoint or certify the complete geom gates.
"""
from fractions import Fraction as F
from math import comb
from hashlib import sha256
from pathlib import Path
import json
import time

HERE = Path(__file__).resolve().parent
OUT = HERE / "ordered_propagation_endpoint_guard_results_20261007.json"
REG = HERE / "ordered_propagation_endpoint_registration_20261007.json"
assert REG.exists() and not OUT.exists(), "Preserve registration and all prior run results"

def receipt(q):
    def digest(k):
        return sha256(k.to_bytes((k.bit_length()+7)//8, "big")).hexdigest()
    return {
        "float_display_only": float(q),
        "numerator_bits": q.numerator.bit_length(),
        "denominator_bits": q.denominator.bit_length(),
        "numerator_binary_sha256": digest(q.numerator),
        "denominator_binary_sha256": digest(q.denominator),
    }

started = time.time()
rounds = []
for n in (512, 1024, 4096):
    k = n.bit_length()-1
    assert 1 << k == n
    eps = F(1, 100*n*n)
    cut = F(12+k//2, n)
    denominator = n**n
    numerator = sum(comb(n,j)*j**j*(n-j)**(n-j) for j in range(n+1))
    D = F(numerator, denominator)
    survival = (1-F(2,n))**n
    late = (1-cut)**n
    omitted = late+F(2,n)
    lower = survival*(D-1)-D*omitted
    tests = {
        "cell_contains_initial_density": eps < F(1,2*n),
        "source_is_in_early_half": 0 < cut < F(1,2),
        "cut_at_least_16_over_n": cut >= F(16,n),
        "original_w_floor_from_peak_and_tail": 4*eps+F(1,2**n) <= F(1,n),
        "late_at_most_2_minus_16": late <= F(1,2**16),
        "survival_at_least_1_over_16": survival >= F(1,16),
        "D_at_least_two": D >= 2,
        "D_ratio_at_most_two": D <= 2*(D-1),
        "twice_omitted_below_1_over_32": 2*omitted < F(1,32),
        "lower_at_least_Dminus1_over_32": lower >= (D-1)/32,
        "Dminus1_squared_at_least_n_over_16": (D-1)**2 >= F(n,16),
        "lower_squared_at_least_n_over_16384": lower**2 >= F(n,128**2),
    }
    assert all(tests.values()), (n, tests)
    rounds.append({
        "n": n, "epsilon": str(eps), "early_cutoff": str(cut),
        "D": receipt(D), "late": receipt(late), "strong_lower": receipt(lower),
        "tests": tests,
    })

result = {
    "status": "PASS_EXACT",
    "checks": sum(len(r["tests"]) for r in rounds),
    "registration_sha256": sha256(REG.read_bytes()).hexdigest(),
    "script_sha256": sha256(Path(__file__).read_bytes()).hexdigest(),
    "elapsed_seconds": time.time()-started,
    "rounds": rounds,
    "scope": "Original first-event exit subsource strong-L1 lower coefficient guard. No weak endpoint or actual geom gate certification.",
}
OUT.write_text(json.dumps(result, ensure_ascii=False, indent=2)+"\n")
print(json.dumps({"status":result["status"],"checks":result["checks"],
                 "elapsed_seconds":result["elapsed_seconds"],
                 "rows":[{"n":r["n"],"D":r["D"]["float_display_only"],
                          "strong_lower":r["strong_lower"]["float_display_only"]} for r in rounds]}))
